version: '3'

services:
  database:
    container_name: db-delivery
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: deliveryfood

  server:
    container_name: server-delivery
    image: kennedyaquino/delivery-server
    environment:
      DB_HOST: database
    ports:
      - 8080:8080